### PR TITLE
Adhering to SPDX standard for licence naming

### PR DESCRIPTION
**Pull request by camillem**
Following SPDX standard would  reduce ambiguity, improve interoperability and eases legal compliance.
Thanks !

### CODE REVIEW

**Comment by AltGr** [comment]
That would indeed be a very good thing for classification, thanks! Didn't know about the SPDC standard. We would need to implement the list and check it in `opam lint`.

One concern is that, although it hasn't been validated to date, lots of packages use the LGPL "with OCaml linking exception" [1] ; and this isn't listed [here](http://spdx.org/licenses/exceptions-index.html).

[1] From http://caml.inria.fr/ocaml/license.en.html:

> As a special exception to the GNU Library General Public License, you may link, statically or dynamically, a "work that uses the Library" with a publicly distributed version of the Library to produce an executable file containing portions of the Library, and distribute that executable file under terms of your choice, without any of the additional requirements listed in clause 6 of the GNU Library General Public License. By "a publicly distributed version of the Library", we mean either the unmodified Library as distributed by INRIA, or a modified version of the Library that is distributed under the conditions defined in clause 3 of the GNU Library General Public License. This exception does not however invalidate any other reasons why the executable file might be covered by the GNU Library General Public License.

**Comment by camillem** [comment]
Hi, 
It is fairly simple to have the exception added to the list. It just takes an email to spdx-legal@lists.spdx.org (see http://spdx.org/spdx-license-list/request-new-license) with the following elements. If you're ok with the proposed name and ID for the licence, I can take care of that.

- Provide a proposed Full Name for the license or exception :"OCaml linking exception"
- Provide a proposed Short Identifier : "OCaml-exception"
- Provide a functioning url reference to the license or exception text, either from the author or a community recognized source : http://caml.inria.fr/ocaml/license.en.html
- Create and attach a text file with the license or exception text from the url provided in #3. Please proofread the text file to ensure that:
    - Information has not been lost or modified.
    - Formatting is clean and consistent with the license or exception URL.
- Indicate whether the license is OSI-approved [Yes/No] (see: http://www.opensource.org/licenses/alphabetical). If yes, provide link to the OSI license and verify that it is the same text as supplied in #4. : No
- Provide a short explanation regarding the need for this license or exception to be included on the SPDX License List, including identifying at least one program that uses this license. : it is currently used in many packages, which is a blocker for them to use SPDX in their packaging guidelines (see https://github.com/ocaml/opam/pull/2224#issuecomment-116399045 )

**Comment by AltGr** [comment]
This sounds good, thanks a lot if you can take care of it!
There is also a small modification to the QPL license for the OCaml tools themselves, but I don't think it matters much, and it's only used once AFAIK.

**Comment by AltGr** [comment]
@rdicosmo, still no response on the validation of our "OCaml linking exception" from the FSF ?

**Comment by rdicosmo** [comment]
Not that I know, let me check with @zacchiro

On Tue, May 02, 2017 at 06:29:25AM -0700, Louis Gesbert wrote:
> @rdicosmo, still no response on the validation of our "OCaml linking exception"
> from the FSF ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Roberto

**Comment by zacchiro** [comment]
Re: "OCaml linking exception", yes, there are news.

As a background: we approached the FSF a while ago, presenting the specific needs of the OCaml language and runtime, and proposing a specific exception text which I drafted, with reviews from @rdicosmo as well as an experienced international FOSS lawyer. Just a few days ago the FSF got back to us, with an alternative proposal, which looks good too.

They have been busy at the FSF with other urgent legal stuff, but they are now on this and willing to prioritize it so that we can quickly reach a final exception proposal for the OCaml community.

I'll keep you posted as soon as I've (additional) news.

**Comment by lefessan** [comment]
Wonderful !

**Comment by AltGr** [comment]
Great, thanks a lot!

**Comment by nbraud** [comment]
@zacchiro What's the status on this?

**Comment by zacchiro** [comment]
@nbraud no news, and I don't think I can do anything else to speed things up. I'll just followup once more via email, pointing the FSF to this issue, and saying I'm giving up. There is no point in having an additional middle man (me). I'll be happy to share the proposed exception text to anyone who wants to pick this up.

**Comment by hnrgrgr** [comment]
It looks like an OCaml linking exception has been registred in the SPDX database since last october:

  https://spdx.org/licenses/OCaml-LGPL-linking-exception.html
  https://github.com/spdx/license-list-XML/issues/649

@zacchiro Is that related to your initial effort ?

**Comment by zacchiro** [comment]
On Tue, Feb 05, 2019 at 03:51:37AM -0800, Grégoire Henry wrote:
> It looks like an OCaml linking exception has been registred in the SPDX database since last october:
> 
>   https://spdx.org/licenses/OCaml-LGPL-linking-exception.html
>   https://github.com/spdx/license-list-XML/issues/649
> 
> @zacchiro Is that related to your initial effort ?

Not that I know of, but I'm not particularly surprised.

The process of updating the SPDX license list is driven by industrial
users that uses SPDX for software bill of materials and encounter code
in the wild under a license not yet on the list. A few real-life
occurrences of the problem are generally enough to obtain an addition.

I'm guessing that is what happened here, but I've no idea about *who* is
the "patient zero" in this case :-)

Cheers

**Pull request closed without merging**
