### PR TITLE
Updates for OCaml 4.07.1

### PR DESCRIPTION
**Pull request by dra27**
- Three tweaks to the `src_ext` vendoring script.
 - Minor fix to AppVeyor bootstrap compaction
 - Shift the cold compiler to 4.07.~0~1 and include 4.07.~0~1 in the test matrix
 - ~Disable Cygwin64 testing - it's been only been enabled because the cached copy of OCaml 4.06.0 was still in place. flexdll needs patching, I've nagged the guy who wrote the patch to finish it...~ (cherry-picked in cac57424)

### CODE REVIEW

**Comment by dra27** [comment]
Oh dear - that last commit is a bit worrying!

**Comment by dra27** [comment]
@pmetzger - just for interest (apropos of #3455), that final commit is an example of `make -j` causing problems with OCaml 4.07.0 (still trying to investigate why, sadly...)

**Comment by pmetzger** [comment]
@dra27 🙁

**Comment by pmetzger** [comment]
@dra27 I wonder if there's some way we could build something to deliberately exercise lots of randomized build orderings in order to shake out the make -j issue. But that should be discussed in the OCaml mantis or some such I suspect.

**Comment by dra27** [comment]
Given that it’s repeatable, and apparently only affecting this specific platform, I fear it will turn out to be an annoying `make` thing...

**Comment by pmetzger** [comment]
Just one note: Travis has a fairly short timeout based on wall clock time and not on CPU time. (Dumb I think, but I didn't design Travis.) I don't think that will cause problems for this in particular, but you should be aware of it in case it comes up.

**Comment by dra27** [comment]
The build cache is being a nuisance here - https://travis-ci.org/dra27/opam/builds/407124218 is running with the caches blown away

**Comment by dra27** [comment]
Just a ping on this one - rebased and good-to-go

**Comment by rjbou** [comment]
Great! Thanks!

**Pull request merged**
