### PR TITLE
Fish integration: nitpicking

### PR DESCRIPTION
**Pull request by ElectreAAS**
This PR is the third and last off-shoot of #5802, containing the only bugfix in the previous PR: this change `isatty -> status is-interactive`.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you rebase on top of master? the two tests are conflicting

**Comment by ElectreAAS** [comment]
Done :)

**Comment by kit-ty-kate** [comment]
LGTM, could you update the changelog (master_changes.md) with this change? If you don't know what to put we can do it for you.

**Review by rjbou — APPROVED** [review]

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks

**Pull request merged**
