### PR TITLE
Allow <name>.opam in the source of packages

### PR DESCRIPTION
**Pull request by AltGr**
Convenient when there are several packages compiled from the same repo

### CODE REVIEW

**Comment by avsm** [comment]
Can this be a provisional feature for 1.2.1 :)

**Comment by dbuenzli** [comment]
Could you please document the exact behaviour in `opam pin --help`

**Comment by AltGr** [comment]
@avsm: offers more options when pinning, but doesn't affect the repo and base usage, so that should be OK.
@dbuenzli: sure, will do. The idea is that when pinning `pkg` to `dir`, instead of just looking for an opam file at `dir/opam` (or `dir/opam/opam`), it will prefer a `dir/pkg.opam` (or `dir/pkg.opam/opam`).

**Comment by AltGr** [comment]
So unless you have `*.opam` files lying around, previous behaviour should be unchanged.

**Comment by dbuenzli** [comment]
Yes, I read the code... I'm just being annoying so that the docs remain up-to-date (also often trying to write documentation of features first/simultaneously is a good usability test: if you can't explain it well you certainly have something wrong). Make sure the priority list for selection is explicitly documented. 

That being said in the subopams case we now have a strong link between the name we pin to and the opam files that need to be present. This is not the case if you don't have subopams, you can do for example `pin add fancy xmlm-repo` (vs. the expected `pin add xmlm xmlm-repo`) which may have its uses (does it ?). So if you face a repo with subopams you cannot do that. This asks whether maybe an `--opam-file=PATH` where `PATH` is a file path relative to the pinned repo should be added to be able to explicitly tell which opam file you want to select.

**Pull request merged**
