### PR TITLE
Build the man-pages using dune

### PR DESCRIPTION
**Pull request by AltGr**
this avoids a big annoyance on every `make install`

### CODE REVIEW

**Comment by AltGr** [comment]
@dra27 an idea what's still blocking here ?

**Comment by dra27** [comment]
See the PR I made on the OCamlPro repo - I have another commit to push in a sec

**Comment by dra27** [comment]
Here's the diff with the old `opam-actual.install`:
```diff
--- opam.install	2019-07-04 16:27:03.845855812 +0100
+++ opam-actual.install	2019-07-04 16:29:52.726094232 +0100
@@ -1,27 +1,14 @@
-lib: [
-  "_build/install/default/lib/opam/META"
-  "_build/install/default/lib/opam/dune-package"
-  "_build/install/default/lib/opam/opam"
-]
 bin: [
   "_build/install/default/bin/opam"
 ]
 doc: [
-  "_build/install/default/doc/opam/CHANGES"
-  "_build/install/default/doc/opam/LICENSE"
-  "_build/install/default/doc/opam/README.md"
 ]
 man: [
-  "_build/install/default/man/man1/opam-admin-add-constraint.1"
-  "_build/install/default/man/man1/opam-admin-add-hashes.1"
   "_build/install/default/man/man1/opam-admin-cache.1"
-  "_build/install/default/man/man1/opam-admin-check.1"
   "_build/install/default/man/man1/opam-admin-filter.1"
-  "_build/install/default/man/man1/opam-admin-help.1"
   "_build/install/default/man/man1/opam-admin-index.1"
   "_build/install/default/man/man1/opam-admin-lint.1"
   "_build/install/default/man/man1/opam-admin-list.1"
-  "_build/install/default/man/man1/opam-admin-make.1"
   "_build/install/default/man/man1/opam-admin-upgrade.1"
   "_build/install/default/man/man1/opam-admin.1"
   "_build/install/default/man/man1/opam-clean.1"
@@ -32,6 +19,7 @@
   "_build/install/default/man/man1/opam-info.1"
   "_build/install/default/man/man1/opam-init.1"
   "_build/install/default/man/man1/opam-install.1"
+  "_build/install/default/man/man1/opam-installer.1"
   "_build/install/default/man/man1/opam-lint.1"
   "_build/install/default/man/man1/opam-list.1"
   "_build/install/default/man/man1/opam-lock.1"
```

**Comment by dra27** [comment]
So, there seem to be the following things left to check/resolve:
- We're affected by https://github.com/ocaml/dune/issues/2353, so the `lib` section should disappear in the future (but we'll need to post-process the file on the `2.0` branch to get rid of that)
- We're no longer install `opam-installer.1` - however, we don't actually install `opam-installer` by default. I'm not sure if that's on purpose, or not. We should only install `opam-installer.1` if we also install `opam-installer` (which we possibly should??) **and** we should also make sure that `opam-installer.install` (i.e. the separate package) builds `opam-installer.1`.
- We're installing some doc files, which is going to exacerbate #3552 and #3711
- This process has definitely caught some missing `opam admin` subcommands!

**Comment by dra27** [comment]
This is enough to get `opam-installer.1` in the `opam-installer` package:
```diff
diff --git a/doc/man/dune b/doc/man/dune
index 4dd4c3b2..2c5a27d6 100644
--- a/doc/man/dune
+++ b/doc/man/dune
@@ -8,6 +8,14 @@
   (package opam)
   (files opam.1))
 
+(rule
+  (with-stdout-to opam-installer.1 (run %{bin:opam-installer} --help=groff)))
+
+(install
+  (section man)
+  (package opam-installer)
+  (files opam-installer.1))
+
 (executable
   (name dune_man)
   (libraries unix))
```

**Comment by AltGr** [comment]
Superseded by #3937 (thanks @dra27 !)

**Pull request closed without merging**
