### PR TITLE
Added alternate way to get opam_installer.sh

### PR DESCRIPTION
**Pull request by mars0i**

### CODE REVIEW

**Comment by dra27** [comment]
Follows on from #2898

**Comment by AltGr** [comment]
Thanks!
Same note as for #2941: this won't be visible on the main doc pages unless merged into the 1.3 branch.

**Comment by AltGr** [comment]
Arg, forgot to ask for rebase or squash. Please cleanup your branch before PRs :p

**Comment by mars0i** [comment]
OK, just to be sure I have the right idea, I think that if I just insert my new text into the appropriate place in 1.3 and make a single commit of it, that will allow me to create a clean pull request for 1.3.  Is that what I should do?  Is there anything further I ought to do with respect to the master branch?  Thanks.

**Pull request merged**
