### PR TITLE
Bump compat releases (for 4.09.0 with dune 2.3.0) 

### PR DESCRIPTION
**Pull request by tuncer**
Same as #4097, but against master.

### CODE REVIEW

**Comment by tuncer** [comment]
This diff is the same as #4097, but it fails to build `src_ext/cmdliner` for some reason, even though no such error happens in #4097. I suspect a difference between `master` and `2.0`, not sure what. Any ideas?

**Comment by dra27** [comment]
2.0 shouldn’t have deps bumped until it’s absolutely necessary (cmdliner was already lagging)

**Comment by tuncer** [comment]
It's what I had to change to make it work, but I know it's tricky to support a wide range of OCaml switches. @dra27, let's continue the discussion in #4097, if you don't mind.

**Comment by dra27** [comment]
This is superseded by #4257

**Pull request closed without merging**
