### PR TITLE
remove insecure / no-check-certificate flags (see mail on opam-devel, #55 #2006)

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
(earlier discussion in #55 #2006) -- also, I do use `download-command: [ "fetch" url "-o" out ]` in my `.opam/config` (which authenticates server certificates), so far without problems)

**Comment by hannesm** [comment]
To add some more data, figuring out which https hosts are used in the main opam-repository:
```
2401 github.com
 924 ocaml.janestreet.com
 209 forge.ocamlcore.org
 159 bitbucket.org
  31 gforge.inria.fr
  10 raw.github.com
   6 codeload.github.com
   5 www.lri.fr
   4 people.cs.umass.edu
   4 downloads.sf.net
   3 coq.inria.fr
   1 zoggy.github.io
   1 pkgs.fedoraproject.org
   1 gmplib.org
```

and it turns out, pkgs.fedoraproject.org does not send its full certificate chain (used in zenon, others (omake & findlib) use http on pkgs.fedoraproject.org).  thus, the numbers arein favour of the change (and zenon and/or pkgs.fedoraproject.org should be fixed!)

**Comment by avsm** [comment]
the fedoraproject url is a fallback for missing upstream distfiles; we could host those elsewhere on ocaml.org with a proper cert

**Comment by hannesm** [comment]
sounds good to me!

**Comment by AltGr** [comment]
Thanks!

**Pull request merged**
