### PR TITLE
Update `OpamAction.install_package` documentation

### LINKED ISSUE #5207: OpamAction.install_package documentation inaccuracy
The documentation speaks of returning `None` or `Some exn` while the type says it returns an `Either.t` (roughly).
https://github.com/ocaml/opam/blob/257152247d275257d1c9e30c7be91db47c56109c/src/client/opamAction.mli#L53-L58

### PR DESCRIPTION
**Pull request by rjbou**
Closes #5207

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @reynir Does this look good?

**Comment by reynir** [comment]
Yes, this addresses my issue.

> Do not update opam's metadata

Is this because `OpamAction.install_package` handles this?

**Comment by rjbou** [comment]
Oups, i made a mistake on the title

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
