### PR TITLE
release script: Add ppc64le and s390x support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Both of them are now present in the multiarch/alpine images: https://hub.docker.com/r/multiarch/alpine

### CODE REVIEW

**Comment by dra27** [comment]
Cool!

**Comment by rjbou** [comment]
What is the status of this PR?

**Comment by kit-ty-kate** [comment]
> What is the status of this PR?

we just need to check that the resulting binaries actually work

**Comment by rjbou** [comment]
binaries checked, good to go

**Review by rjbou — APPROVED** [review]

**Comment by rjbou** [comment]
Thanks!

**Pull request merged**
