### PR TITLE
Don't error out with --no-switch flag if compiler is installed

### LINKED ISSUE #1813: `opam switch doc -A system --no-switch` gives an error if the compiler exists
`opam switch doc -A system --no-switch` gives an error if the compiler exists, which the documentation for `--no-switch` explicitly says it will not.

We use this in the old opam-doc prototype, which no longer works with opam 1.2. (It will also soon be deprecated so this is not particularly important).

### PR DESCRIPTION
**Pull request by anemator**
Fixes #1813.

### CODE REVIEW

**Comment by AltGr** [comment]
Thanks!

The check on the dirname existence is not just here to check if the switch exists though, but also to prevent accidental overwrite: swiches directories are at `~/.opam/` and share the namespace with directories like `repo` and `packages` -- we really want to fail in case someone tries `opam switch install repo http://xxx`.

According to the doc, `opam switch install x` _should_ fail when the switch `x` is already installed, while `opam switch x` (which is an alias for `opam switch set x`) should continue. I think what is really missing here is that the `--no-switch` option isn't honored by `switch set`.

**Comment by AltGr** [comment]
There could be a test on the switch existence before the check for the directory existence, still, though.

**Comment by anemator** [comment]
Thanks for the info!

```--no-switch``` doesn't seem applicable to ```switch set``` according to the documentation: "Set the currently active switch, installing it if needed." Ideally, I'd like to ignore ```--no-switch``` on ```switch set```, but I'm concerned that will break user scripts.

**Comment by AltGr** [comment]
> Ideally, I'd like to ignore --no-switch on switch set, but I'm concerned that will break user scripts.

I think that's how it behaves at the moment.

**Comment by AltGr** [comment]
Thanks a bunch, all good, sorry for the lag!

**Pull request merged**
