### PR TITLE
Fix regression on the concurrent lock message

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by dra27** [comment]
`%!` can't be used any more - can't remember the detail, but this isn't the right fix.

**Comment by dra27** [comment]
(that's a TODO list item for me as in the middle of a rehearsal!)

**Comment by dra27** [comment]
Looking at the definition, shouldn't `formatted_msg` be flushing already (see definition of `OpamConsole.print_message`)?

**Comment by AltGr** [comment]
Probably didn't look closely enough... but it definitely wasn't flushing the unfinished line!

**Comment by dra27** [comment]
It’s going ksprintf, so the `%!` shouldn’t be doing anything - is there another effect?

**Comment by AltGr** [comment]
Indeed, the channel should be flushed... and can't reproduce today, must have seen an artifact. Sorry for the noise, will dig more if it happens again.

**Pull request closed without merging**
