### PR TITLE
Filter commits so the curves are increasing

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
The resulting images:
contributors
packages
unique-packages

**Comment by Chris00** [comment]
BTW, this command takes way too long (30 mins) and uses way too much memory (1.7 Gb).  Is there a reason why the data is not collected *per commit* and the accumulation done by the program (which should allow sharing memory between the buckets).

**Comment by samoht** [comment]
>  Is there a reason why [...]

lazyness :p you are very welcome to improve my crappy scripts!

**Comment by avsm** [comment]
Looks significantly better!  Would it be possible to start from the first data point to avoid the big import at 10/2012?

**Comment by Chris00** [comment]
New versions:
contributors
packages
unique-packages

**Comment by Chris00** [comment]
@samoht OK.  I'll see if I have some time...

**Comment by avsm** [comment]
Hurrah, that looks great!

**Pull request merged**
