### PR TITLE
2.0.8 backported commits

### LINKED ISSUE #4068: Regression: Opam 2.0.6 fails any build with cache-related bwrap error [cache as link]
Possibly related to #4012, after updating from 4.0.5 to 4.0.6 I can no longer upgrade anything.  I consistently get, for packages I tried (`ppx_tools`, `dune`):

```text
### output ###
# bwrap: Can't mkdir /home/lis/.cache/dune: No such file or directory
```

Note that in my setup, `/home/lis/.cache` is a symbolic link to `/tmp/` (which is in RAM with `tmpfs`). If I remove directory `/tmp/dune` it does get re-created, despite what the above error implies.

Downgrading to 4.0.5 restores normal behavior, hence my suspicion that opam may be at fault.

```text
lis@titanium:~$ opam config report
# opam config report
# opam-version      2.0.6
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=10.2
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at 4585683c)
# pinned            0
```

### LINKED ISSUE #4078: `opam env` adds . to PATH in fish shell
When I execute `eval (opam env)`, I end up with `.` in my `PATH`.

I think the problem is caused by an extra colon in the output of `opam env`:

```
set -gx PATH ':/home/bertrand/.opam/4.07.1/bin' '/usr/local/sbin' '/usr/local/bin' '/usr/bin' '/usr/bin/site_perl' '/usr/bin/vendor_perl' '/usr/bin/core_perl';
```

It results in:

```
> echo $PATH
. /home/bertrand/.opam/4.07.1/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

## opam config report

```
# opam config report
# opam-version      2.0.6 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=arch os-version=unknown
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http), 1 (version-controlled) (default repo at 203e326c)
# pinned            1 (git), 1 (rsync)
# current-switch    4.07.1
```

### LINKED ISSUE #4079: Sandbox script doesn't work with newer versions of ccache
[It seems](https://ccache.dev/releasenotes.html#_ccache_3_7) that ccache 3.7 changed the name of its `--print-config` argument to `--show-config`. This means that the sandboxing script is now broken if you use ccache with a customized `ccache_dir`. It seems that `--print-config`/`--show-config` is available as `-p` both before and after the rename -- so the easiest fix is probably to use that.

### LINKED ISSUE #4173: Compilation of opam-installer failed
I am trying to build opam HEAD from source and encountering a compilation issue with opam-installer. I already have opam 2.0.5 (obtained via ubuntu apt install).

```
$ opam config report
# opam config report
# opam-version      2.0.5 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=ubuntu os-version=20.04
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              2
# repositories      1 (http) (default repo at 88a179f5)
# pinned            8 (git)
# current-switch    /home/abcxyz/opam

$ git clone https://github.com/ocaml/opam.git

$ cd opam

$ git rev-parse HEAD
3def1a6d1ff102aaa608f5e9170783b96f55069d

$ opam switch create . ocaml-system.4.08.1

$ opam install . --deps-only

////// ETC ETC ///// 
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed cmdliner.1.0.4
-> installed conf-m4.1
-> installed conf-perl.1
-> installed ocamlbuild.0.14.0
-> installed ocamlfind.1.8.1
-> installed base-bytes.base
-> installed ocamlgraph.1.8.8
-> installed opam-file-format.2.0.0
-> installed seq.base
-> installed dune.2.5.1
-> installed cppo.1.6.6
-> installed re.1.9.0
-> installed extlib.1.7.7
-> installed cudf.0.9-1
-> installed mccs.1.1+11
-> installed opam-core.2.1.0~alpha
-> installed dose3.5.0.1
-> installed opam-format.2.1.0~alpha
[ERROR] The compilation of opam-installer failed at "/home/abcxyz/.opam/opam-init/hooks/sandbox.sh build make opam-installer.install".
-> installed opam-repository.2.1.0~alpha
-> installed opam-solver.2.1.0~alpha
-> installed opam-state.2.1.0~alpha
-> installed opam-client.2.1.0~alpha
-> installed opam-devel.2.1.0~alpha

#=== ERROR while compiling opam-installer.2.1.0~alpha =========================#
# context     2.0.5 | linux/x86_64 | ocaml-system.4.08.1 | pinned(git+file:///home/abcxyz/opam#master#3def1a6d)
# path        ~/opam/_opam/.opam-switch/build/opam-installer.2.1.0~alpha
# command     ~/.opam/opam-init/hooks/sandbox.sh build make opam-installer.install
# exit-code   2
# env-file    ~/.opam/log/opam-installer-306825-783922.env
# output-file ~/.opam/log/opam-installer-306825-783922.out
### output ###
# dune build --profile=release  --promote-install-files opam-installer.install
# Error: Error: mkdir: _build: Read-only file system
# make: *** [Makefile:113: opam-installer.install] Error 1
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build opam-installer 2.1.0~alpha
+- 
+- The following changes have been performed
| - install base-bytes       base
| - install cmdliner         1.0.4
| - install conf-m4          1
| - install conf-perl        1
| - install cppo             1.6.6
| - install cudf             0.9-1
| - install dose3            5.0.1
| - install dune             2.5.1
| - install extlib           1.7.7
| - install mccs             1.1+11
| - install ocamlbuild       0.14.0
| - install ocamlfind        1.8.1
| - install ocamlgraph       1.8.8
| - install opam-client      2.1.0~alpha
| - install opam-core        2.1.0~alpha
| - install opam-devel       2.1.0~alpha
| - install opam-file-format 2.0.0
| - install opam-format      2.1.0~alpha
| - install opam-repository  2.1.0~alpha
| - install opam-solver      2.1.0~alpha
| - install opam-state       2.1.0~alpha
| - install re               1.9.0
| - install seq              base
+- 

<><> opam-devel.2.1.0~alpha installed successfully ><><><><><><><><><><><><><><>
=> The development version of opam has been successfully compiled into /home/abcxyz/opam/_opam/lib/opam-devel. You should not run it from there, please
   install the binaries to your PATH, e.g. with
       sudo cp /home/abcxyz/opam/_opam/lib/opam-devel/opam /usr/local/bin

   If you just want to give it a try without altering your current installation, you could use instead:
       alias opam2="OPAMROOT=~/.opam2 /home/abcxyz/opam/_opam/lib/opam-devel/opam"
# Run eval $(opam env) to update the current shell environment
```

### LINKED ISSUE #4359: Programs called from opam hooks need a way to display information to the user
For `opam-bin`, I would like to display information to the user about what happened during an `opam install` command, for example the number of binary packages that were built, and, if some binary packages could not be built, why, without making the full opam command fail.

A possibility would be to write append some text at the end of a file `$OPAM_SWITCH_PREFIX/.opam-switch/plugins/post-install-message.txt` for example, that would be cleared at the beginning of the session and displayed at the end.

### LINKED ISSUE #4472: pre/post-session-commands ignored in switch config
In Opam 2.0.7, adding a pre/post-session-commands command to a `switch-config` file has no effect (it does in the global config, however). For example, adding 
```
pre-session-commands: [["echo" "test"]]
```
Does not display `test` during installs, even when run in `--verbose` mode.

### PR DESCRIPTION
**Pull request by rjbou**
Backported commits for the 2.0.8 release

## Fish
  * Add colon for fish MANPATH fix. [#4084 @rjbou - fix #4078]

## Sandbox
  * No error when linked directory doesn't exist (e.g. XDG defined) [#4278 @kit-ty-kate]
  * Add quotes to avoid space unwanted behaviors [#4278 @kit-ty-kate]
  * Handle `CCACHE_DIR` environment variable in sandbox script.  [#4087 @rjbou - fix #4079]
  * Follow links of `~/.cache` & `~/.cache/dune` for bwrap call.  [#4087 @rjbou - fix #4068]
  * Don't overwrite user's sandbow script modification. [#4020 #4092 @rjbou]
  * On MacOS sandbox script, always read write mount `/tmp` [#3742 @rjbou - fix ocaml/opam-repository#13339]

## Install
  * The stdout of `pre-` and `post-session` hooks is now propagated to the user [#4382 @AltGr - fix #4359]
  * Run switch pre/post sessions hooks [#4476 @rjbou - fix #4472]

## Build
  * Use version var in opam file instead of equal current version number in opamlib dependencies [#4178 @rjbou]
  * Opam file build using dune [#4178 @rjbou #4229 @kit-ty-kate - fix #4173]
  * Update opam file to 2.0 [#4371 @AltGr]

## Internal
  * Fix `arch` detection when using 32bit mode on ARM64 [#4462 @kit-ty-kate]
  * Fix `arch` detection of i486 [#4462 @kit-ty-kate]

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Would it be possible to vendor https://github.com/ygrek/ocaml-extlib/pull/55 in opam for this release? This would add support for OCaml 4.12 for vendored build mode.

**Comment by rjbou** [comment]
Is it released ?

**Comment by kit-ty-kate** [comment]
> Is it released ?

no, not yet.

**Comment by dra27** [comment]
The patch for it can be dropped in `src_ext/patches/extlib.common/`, yes

**Comment by kit-ty-kate** [comment]
https://github.com/ocaml/opam/pull/4462 might need to be backported as well.

**Comment by hannesm** [comment]
thanks for the 2.0.8 release -- I updated the [FreeBSD port](https://www.freshports.org/devel/ocaml-opam) to 2.0.8, which went smoothly (a `pkg install ocaml-opam` will install the binary package of 2.0.8, built on the FreeBSD package builders). Maybe you want to inform package maintainers of other distributions to update their opam package (see https://repology.org/project/opam/versions).

**Comment by rjbou** [comment]
yes! we have this [page](https://opam.ocaml.org/doc/Distribution.html) to recap distribs/os status, badges from repology ;)
ping @xyproto @mehdid @nbraud  @TC01 @roptat @pmetzger @david-geiger @madroach for this new release!
We should set up a mechanism to ping all maintainers at each release...

**Comment by xyproto** [comment]
The `opam` package in Arch Linux is now at 2.0.8.

It's also possible to flag a package as out-of-date on [this page](https://archlinux.org/packages/community/x86_64/opam/), just in case the `opam` package should ever have a different maintainer, if you're thinking of automating the ping.

Thanks for developing and maintaining opam!

**Comment by roptat** [comment]
Updated in Guix, thanks for the ping!

**Comment by pmetzger** [comment]
I didn't notice this before, but I've now upgraded MacPorts to 2.0.8.

**Comment by mehdid** [comment]
On 2021-02-11 19:32, R. Boujbel wrote:
> yes! we have this page [1] to recap distribs/os status, badges from
> repology ;)
> ping @xyproto [2] @mehdid [3] @nbraud [4] @TC01 [5] @roptat [6]
> @pmetzger [7] @david-geiger [8] @madroach [9] for this new release!
> We should set up a mechanism to ping all maintainers at each
> release...
> 

Thanks for the ping. I've updated opam in Debian (which, fwiw, will 
freeze very soon). Fortunately, 2.0.8 will be part of the next stable 
release.

**Pull request merged**
