### PR TITLE
Track files installed by packages, allow query and use for removal

### LINKED ISSUE #502: Opam should compute the exact list of installed files
It would be nice if opam could uninstall things by logging what got installed in the first place. This is annoying because if you have packages that don't uninstall correctly then reinstalling them doesn't work. This is particularly bad when you do a large 'upgrade' when opam will uninstall a load of packages, reinstall half, break (package maintainer's fault), and then it's up to the user to remember which packages you had installed beforehand!

### PR DESCRIPTION
**Pull request by AltGr**
Closes #502, #1215

### CODE REVIEW

**Comment by Drup** [comment]
So, this works for both `.install` files and the `install` field ? This is great \o/

**Comment by AltGr** [comment]
Yes, it includes all, so this is a bit redundant since it's an added mechanism, but that's not really a problem. Next, I intend to:
- make build dir unneeded by default for `remove:` (removing the need to download archives)
- add an `uninstall-requires-build-dir` flag
- write a repository-rewriting script to add the above flag where necessary or in doubt (using the infamous findlib-hack from opam, and removing it from opam proper)
- update the recommendations for the `remove:` field in the doc: just skip it if you just have to remove the files you added. Retaining the field for documentation is debatable, but since it's often incorrect, if we go that way CI should check that it indeed uninstalled properly (which is now possible).

Packages doing e.g. `make uninstall` will still need their sources though; maybe we could just suppress their `remove:` field in this case. Note that when there is no `remove:` field, the source is never needed, so removing most `remove:` fields rather than changing the download behaviour might be an alternative to the above.

A nice addition would be to not fail, but just skip the `remove:` step if the package archive can't be downloaded but we have a `.changes` file. Probably once I integrate the patch to do the removals as late as possible, and then include downloads in the actions processing graph rather than a first step.

**Comment by AltGr** [comment]
Where's Travis ?

**Comment by AltGr** [comment]
Filing #2571 seems to have wakened up Travis here too (well, it's the same commit). But in both, @github still displays the commits in the wrong order:
I locally have f10af22 *before* 7cf7b8d

**Pull request merged**
