### PR TITLE
Fix `opam switch list-available pkg.version` pattern

### PR DESCRIPTION
**Pull request by arozovyk**
Adresses #6152 
Queued on #6318

### CODE REVIEW

**Review by rjbou — APPROVED** [review]
Thanks! As we discussed, I've reworked the change.

**Review by kit-ty-kate — CHANGES_REQUESTED** [review]
I'm not sure `ands` made sense in general in the first place. I think we should change the behaviour to use `ors` instead.
Otherwise there is no use to allow several parameters. e.g.
```
$ opam switch list-available ocaml-base-compiler ocaml-variants
# Listing available compilers from repositories: kit-ty-kate, default
# No matches found
```
If we switch to `ors` instead we can also simply remove the addition of the `?concat`, which doesn't seem useful to me.

Ideally we should also have a test showing the behaviour of `list-available` with several parameters

**Comment by rjbou** [comment]
If we switch from `ands` to `ors`, it is the purpose of another PR.

**Comment by kit-ty-kate** [comment]
> If we switch from `ands` to `ors`, it is the purpose of another PR.

Done in https://github.com/ocaml/opam/pull/6318. This should be merged first. I've marked this here PR as queued on it.

**Comment by kit-ty-kate** [comment]
rebased

**Comment by kit-ty-kate** [comment]
new proposal queued on top of #6318 with one extra test

**Review by kit-ty-kate — APPROVED** [review]

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
