### PR TITLE
Remove GNUism from bootstrap-ocaml.sh

### PR DESCRIPTION
**Pull request by dra27**
See https://github.com/ocaml/opam/issues/3480#issuecomment-407433227 (and rest of thread)

### CODE REVIEW

**Comment by AltGr** [comment]
should we backport to the 2.0 branch ? :)

**Comment by ilovezfs** [comment]
LGTM.

**Comment by ilovezfs** [comment]
Note there is no 2.0.x in Homebrew yet since you've still designated it prerelease.

**Comment by ilovezfs** [comment]
@AltGr will 2.0.1 be cut from the master branch or the 2.0 branch?

**Comment by dra27** [comment]
I think the plan is to proceed as OCaml does - so PRs committed to master and cherry-picked / separately merged to maintenance branches if deemed appropriate (which this one clearly should be)

**Comment by avsm** [comment]
This would be useful to backport to the 2.0.0 branch so that it builds cleanly... it also affects CentOS and Alpine. It's a pity to release a 2.0.0 which doesn't build cold out of the box :-)

**Comment by rjbou** [comment]
@dra27 Could you rebase this PR on 2.0 branch instead of master?

**Comment by avsm** [comment]
Could this be merged into master first please? That'll unbreak the container builds at least

**Comment by avsm** [comment]
thanks! :)

**Comment by dra27** [comment]
@rjbou - will you cherry-pick this to the 2.0 branch or would you like another PR?

**Comment by rjbou** [comment]
It's ok finally, I merged it to master, to have the fix available, and I'll cherry-pick backports to 2.0 branch.
Thanks!

**Pull request merged**
