### PR TITLE
Improve error message when src directory for repo add doesn't exist

### LINKED ISSUE #5632: `opam` 2.1.4 fails to add a local repository if `opam repo add` is invoked from a "grandparent directory"
Output of `opam config report` as requested:
```
# opam config report
# opam-version         2.1.4
# self-upgrade         no
# system               arch=x86_64 os=linux os-distribution=debian os-version=12
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 3
# repositories         1 (http), 1 (local) (default repo at e46b804c)
# pinned               3 (git)
# current-switch       /home/master/coq
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /home/master/coq/_opam/lib/ocaml/stublibs:/home/master/coq/_opam/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.14.1+options+flambda
```

In this example I was trying to add `opam-coq-archive/released` as a local repository while in a directory `coq` which is the parent directory of `opam-coq-archive`, which results in the following:

```
opam repo add test opam-coq-released/released --debug
00:00.010  CLI                    Parsing CLI version 2.1
00:00.010  GSTATE                 LOAD-GLOBAL-STATE @ /home/master/.opam
00:00.010  RSTATE                 LOAD-REPOSITORY-STATE @ /home/master/.opam
00:00.078  CACHE(repository)      Loaded /home/master/.opam/repo/state-3AF31D16.cache in 0.067s
00:00.078  RSTATE                 Cache found
00:00.078  REPOSITORY             repository-add
00:00.078  SYSTEM                 rm /home/master/.opam/repo/state-3AF31D16.cache
00:00.082  FILE(repos-config)     Wrote /home/master/.opam/repo/repos-config in 0.000s
00:00.082  PARALLEL               Iterate over 1 task(s) with 3 process(es)
00:00.082  PARALLEL               Starting job 0 (worker 1/3): 0
00:00.082  REPOSITORY             update test from file:///home/master/coq/opam-coq-archive/opam-coq-released/released
00:00.082  RSYNC                  pull-repo-update
00:00.082  SYSTEM                 mkdir /home/master/.opam/repo/test.new
00:00.082  SYSTEM                 rmdir /home/master/.opam/repo/test.new
[ERROR] Could not update repository "test": rsync failed
00:00.085  PARALLEL               Job 0 finished
00:00.085  FILE(repos-config)     Wrote /home/master/.opam/repo/repos-config in 0.000s
00:00.085  CACHE(repository)      Writing the repository cache to ~/.opam/repo/state-3AF31D16.cache ...
00:00.441  CACHE(repository)      ~/.opam/repo/state-3AF31D16.cache written in 0.356s
00:00.441  REPOSITORY             repository-remove
00:00.441  SYSTEM                 rm /home/master/.opam/repo/state-3AF31D16.cache
00:00.446  FILE(repos-config)     Wrote /home/master/.opam/repo/repos-config in 0.000s
00:00.446  CACHE(repository)      Writing the repository cache to ~/.opam/repo/state-3AF31D16.cache ...
00:00.802  CACHE(repository)      ~/.opam/repo/state-3AF31D16.cache written in 0.356s
00:00.802  SYSTEM                 rmdir /home/master/.opam/repo/test
[ERROR] Initial repository fetch failed
```

However, if the command is invoked from `opam-coq-archive` or `opam-coq-archive/released` itself, it is fine:

```
opam repo add test released --debug
00:00.009  CLI                    Parsing CLI version 2.1
00:00.009  GSTATE                 LOAD-GLOBAL-STATE @ /home/master/.opam
00:00.010  RSTATE                 LOAD-REPOSITORY-STATE @ /home/master/.opam
00:00.077  CACHE(repository)      Loaded /home/master/.opam/repo/state-3AF31D16.cache in 0.067s
00:00.077  RSTATE                 Cache found
00:00.077  REPOSITORY             repository-add
00:00.077  SYSTEM                 rm /home/master/.opam/repo/state-3AF31D16.cache
00:00.082  FILE(repos-config)     Wrote /home/master/.opam/repo/repos-config in 0.000s
00:00.082  PARALLEL               Iterate over 1 task(s) with 3 process(es)
00:00.082  PARALLEL               Starting job 0 (worker 1/3): 0
00:00.082  REPOSITORY             update test from file:///home/master/coq/opam-coq-archive/released
00:00.082  RSYNC                  pull-repo-update
00:00.314  REPOSITORY             test: applying update from scratch at /home/master/.opam/repo/test.new
00:00.314  SYSTEM                 rmdir /home/master/.opam/repo/test
[test] Initialised
00:00.316  PARALLEL               Next task in job 0: /usr/bin/tar cfz /home/master/.opam/repo/test.tar.gz.tmp -C /home/master/.opam/repo test
Processing  1/1:
00:00.389  PARALLEL               Collected task for job 0 (ret:0)
00:00.907  opam-file              Duplicate descr in '/home/master/.opam/repo/test/packages/coq-mathcomp-analysis/coq-mathcomp-analysis.0.2.2/descr' and opam file
00:01.404  PARALLEL               Job 0 finished
00:01.405  FILE(repos-config)     Wrote /home/master/.opam/repo/repos-config in 0.000s
00:01.405  CACHE(repository)      Writing the repository cache to ~/.opam/repo/state-3AF31D16.cache ...
00:01.777  CACHE(repository)      ~/.opam/repo/state-3AF31D16.cache written in 0.373s
00:01.777  SYSTEM                 rmdir /home/master/.opam/repo/test
00:01.894  FILE(switch-config)    Wrote /home/master/coq/_opam/.opam-switch/switch-config in 0.000s
[NOTE] Repository test has been added to the selections of switch /home/master/coq only.
       Run `opam repository add test --all-switches|--set-default' to use it in all existing switches, or in newly
       created switches, respectively.
```

### PR DESCRIPTION
**Pull request by punchagan**
Closes #5632

### CODE REVIEW

**Comment by rjbou** [comment]
Thanks for the PR. On the general idea, lgtm!
I'll add a test to it, in order to complete it.

**Comment by punchagan** [comment]
> I'll add a test to it, in order to complete it.

There are some existing tests which already fail because of this change. I will go ahead and fix them, to begin with.

**Comment by rjbou** [comment]
I've added a commit that contains the code review & test update.

**Comment by punchagan** [comment]
Thanks for the code improvements and the test fixes, @rjbou !

**Comment by punchagan** [comment]
> Thanks for the code improvements and the test fixes, @rjbou !

Let me know if I need to do anything more to finish this PR, @rjbou ! Thanks!

**Review by rjbou — APPROVED** [review]

**Comment by rjbou** [comment]
I've updated the PR, a review from @kit-ty-kate and it's good to merge!

**Comment by punchagan** [comment]
> Sorry for the delay, we are focusing on the release, and there is only me and partly kate working on opam.

Thank you for your work on opam!

No worries at all -- I'm not in a hurry to have this merged. I just didn't want to leave it hanging there, and wanted clarity on whether it's waiting on me.

**Review by kit-ty-kate — COMMENTED** [review]
Compared to https://github.com/ocaml/opam/pull/6027 I think the errors are less readable. A good error message already exist in the data (the second value of the pair) and duplicating it seems superfluous.

**Comment by rjbou** [comment]
Closing in favor of #6027. Thank you for your proposal!

**Pull request closed without merging**
