### PR TITLE
Update to Jbuilder 1.0+beta17

### PR DESCRIPTION
**Pull request by dra27**
Revised attempt at #3187 (didn't realise I needed to re-open the pull request **before** force pushing the new branch!).

Dependent on https://github.com/ocaml/opam-repository/pull/11329 and a CI pass here.

### CODE REVIEW

**Comment by AltGr** [comment]
This should be ok now ? What's the matter with the appveyor tests  ?

**Comment by dra27** [comment]
Oh, I was working on that in another branch. Hang on!

**Comment by dra27** [comment]
OK, so investigating that I found a few little things which wanted tweaking with the AppVeyor set-up and lib-pkg. This should pass the CI (he says hopefully)...

**Comment by AltGr** [comment]
Thanks!

**Pull request merged**
