### PR TITLE
Update src_ext dependencies

### PR DESCRIPTION
**Pull request by abate**
Add cppo (to compile extlib and dose3)

extlib: 1.5.3 -> 1.7.0
dose3: 3.3 -> 4.3
ocamlgraph: 1.8.5 -> 1.8.6

### CODE REVIEW

**Comment by abate** [comment]
I guess travis is not configured to test the src_ext makefile...

**Comment by AltGr** [comment]
Travis tests both the src_ext mode (with `OPAMTEST=`) and the mode with external dependencies (with `OPAMTEST=1`), which is needed to build opam-rt.
There is a weird failure for cppo with src_ext though (from https://travis-ci.org/ocaml/opam/jobs/127840589#L385) :
```
ocamlopt -o cppo -dtypes unix.cmxa str.cmxa cppo_version.ml cppo_types.ml cppo_parser.mli cppo_parser.ml cppo_lexer.ml cppo_command.ml cppo_eval.ml cppo_main.ml

cd ocamlbuild_plugin && ocamlbuild -use-ocamlfind ocamlbuild_cppo.cma ocamlbuild_cppo.cmxa ocamlbuild_cppo.a ocamlbuild_cppo.cmxs

+ ocamlfind ocamldep -package ocamlbuild -modules ocamlbuild_cppo.mli > ocamlbuild_cppo.mli.depends

/bin/sh: 1: ocamlfind: not found

Command exited with code 127.
```

Without src_ext, opam-rt doesn't compile because it tries its `master` branch (the script will choose the `next` branch of opam-rt if you make a PR _from_ a branch named `next`, but it seems it's not clever enough to choose that branch if you make a PR _to_ the `next` branch. Feel free to fix it, or just rename your local branch...)

Also, don't expect tests to get green right now anyway, they break (later) on next, but I am precisely in the process of fixing them, after which I'll merge `next` into `master`, and hopefully release `2.0~alpha`.

**Comment by AltGr** [comment]
Tests should now pass, and next has been merged so could you please re-submit to master ?

It should solve the issue with `opam-rt`. It seems the only other [issue remaining](https://travis-ci.org/ocaml/opam/jobs/129150610#L570) is with our src_ext build system on 4.01 for extlib 1.7, which probably relies on the compat Bytes implementation. I guess solutions could include puting that somewhere in src_ext, patching extlib or reverting to the previous version.

**Comment by AltGr** [comment]
Note that the `Bytes` issue is not extlib specific, and I remember having a similar one on the latest version or `Re`; so including a version of the compat Bytes modules may be a good idea anyway, I will have a look.

Ah, and forgot to thank you for the PR! ☺

**Pull request closed without merging**
