### PR TITLE
Improvements to `opam list` and `opam show`

### PR DESCRIPTION
**Pull request by AltGr**
Thanks @Drup for the feedback!

### CODE REVIEW

**Comment by Drup** [comment]
I guess it's not possible to give a list of the possible fields in the man page ?

**Comment by AltGr** [comment]
@Drup from `opam show --help`:
```
       -f FIELDS, --field=FIELDS
           Only display the values of these fields. Fields can be selected
           among name, version, package, synopsis, synopsis-or-target,
           description, <field>:, installed-version, pin, opam-file,
           all-installed-versions, available-versions, all-versions,
           repository, installed-files. Multiple fields can be separated with
           commas, in which case field titles will be printed; the raw value
           of any opam-file field can be queried by suffixing a colon
           character (:), e.g. --field=depopts:.
```
Or did you mean the list of all "opam-file field[s]" ? This could be extracted too, but we need to remove the ones that exist for backwards compatibility only.

**Comment by Drup** [comment]
Ah, I meant "flag", sorry!

**Comment by AltGr** [comment]
They are listed in `opam list`:
```
       --has-flag=FLAG
           Only include packages which have the given flag set. Package flags
           are one of: light-uninstall verbose plugin compiler conf
```
Tags are not, obviously, since they are free-form strings.

**Comment by Drup** [comment]
I missed that one! Great.

**Pull request merged**
