### PR TITLE
Don't remove git cache objects that may be used

### PR DESCRIPTION
**Pull request by AltGr**
This is a quickfix, we can probably do better than that ; see #3828

### CODE REVIEW

**Comment by erikmd** [comment]
Hi @rjbou @AltGr, I've seen you put the milestone 2.1.0 for this PR #3831 (which will be important to be able to run `opam clean -c` again in `coqorg/coq:dev`-based images and thus save ~110MB…)

Do you confirm that the upcoming release of opam will be 2.1.0, or do you plan to make a point release 2.0.x beforehand? (in which case would this PR be eligible to be shipped along?)

**Comment by erikmd** [comment]
@rjbou @AltGr actually I've just seen that you opened some [milestone for 2.0.6](https://github.com/ocaml/opam/milestones) :-)

Hence my question: would it be feasible for you to integrate the fix from PR #3831 in opam 2.0.6 ?

Kind regards, Erik

**Comment by rjbou** [comment]
There will be 2.0.6 & 2.1.0~beta releases. What we plan is that the 2.0 branch is the LTS one until 2.2.0, and its releases contains only bug fixes. By default, all PR are tagged 2.1.0 until backported to 2.0 branch for a release (cf. backported commits PRs).
We can integrate then this PR into 2.0.6.

**Comment by erikmd** [comment]
OK great! Thanks @rjbou for your explanation :+1:

**Pull request merged**
