### PR TITLE
Fix 4.06 compatibility

### PR DESCRIPTION
**Pull request by tuncer**
This boils down to three src_ext changes:

1. Switch to 4.06-compatible ocamlgraph-1.8.8 release.
2. Drop Bytes->String patch for re.
3. Add Damien's safe-strings patch for dose3.
   Source:
   https://gforge.inria.fr/tracker/index.php?func=detail&aid=21552&group_id=4395&atid=13810
   https://gforge.inria.fr/tracker/download.php/4395/13810/21552/6082/0001-fixes-for-4.06-safe-string.patch

### CODE REVIEW

**Comment by tuncer** [comment]
Would be nice to get a new dose3 release with 4.06 support, but it's okay to apply @damiendoligez's patch for now.

**Comment by tuncer** [comment]
One CI job failed, but the cause is unrelated and a general Travis-CI error.

**Comment by dra27** [comment]
I was working on 4.06 support in the Windows branch last night - are you sure this worked, I needed extlib patches too?

You could usefully push a change to .travis.yml to add 4.06.0 to the test matrix in this pull request.

**Comment by tuncer** [comment]
Here's I how built:

```
$ git clean -fxd
$ ./configure
$ make lib-ext
$ make
```

With 4.06.0+flambda on linux-amd64 it works in this branch but not on master.

Good idea, will look at updating travis-ci.yml.

**Comment by tuncer** [comment]
Pushed build matrix extension.

**Comment by tuncer** [comment]
CI fails for 4.06 with an error I haven't seen locally:

```
        cppo src_ext/dose3/common/criteria_parser.pp.mli
    ocamlopt src/core/opamSHA.{cmx,o} (exit 2)
(cd _build/default && /home/travis/.opam.bootstrap/4.06.0/bin/ocamlopt.opt
  -w -40 -w +a-4-44-48 -warn-error A -safe-string -g
  -I/home/travis/.opam.bootstrap/4.06.0/lib/ocaml
  -I src_ext/ocamlgraph/lib -I src_ext/ocamlgraph/src -I src_ext/re/lib
  -no-alias-deps -I src/core -o src/core/opamSHA.cmx
  -c -impl src/core/opamSHA.ml)
File "src/core/opamSHA.ml", line 114, characters 17-32:
Error (warning 3): deprecated: B.Array1.map_file
Use [array1_of_genarray (Unix.map_file ...)] instead.
Note that Bigarray.Array1.map_file raises Sys_error while
Unix.map_file raises Unix_error.
make: *** [opam.install] Error 1
```

Any guess what's different on Travis? Does opam's Makefile maybe consider stuff found in `~/.opam/`? I don't think it does.

**Comment by dra27** [comment]
CI builds with `-warn-error`. You can add that locally by adding `--enable-developer-mode` to your `./configure` invocation.

**Comment by tuncer** [comment]
@dra27, that explains it.

What's the plan? Merge this and then #3150, or merge either branche's commits into the other and then close one of them?

**Comment by AltGr** [comment]
Thanks!

**Comment by tuncer** [comment]
@AltGr, this branch has the minimum set of changes to make opam build and work with 4.06.0. I've been using the opam binary for over a week. Also, since #3150 makes further changes related to 4.06.0 support but isn't ready yet, I would prefer to merge this first and give #3150 time to be completed. That way, 4.06.0 would be supported for the basic `./configure && make lib-ext && make install` use case.

**Comment by dra27** [comment]
Um, FWIW #3150 is finished and also has the benefit of passing CI...

**Comment by tuncer** [comment]
Cool, I guess we can close this in favor of #3150, then. Should we wait for #3150's CI?

**Comment by dra27** [comment]
I'm sure Travis will manage to spin-up that last macOS job before @AltGr starts work tomorrow!

**Comment by tuncer** [comment]
Unless I'm reading it wrong, you suggest we should close this, right?

**Comment by tuncer** [comment]
I would like to extend the build matrix in order to have opam support 4.07.0 on release day. Would it be incorrect if I added `OCAML_VERSION=4.07.0+trunk+flambda` in `.travis.yml`? If it doesn't succeed yet, is there a mechanism to tag the entry as may-fail?

**Comment by tuncer** [comment]
Closing in favor of #3150.

**Comment by AltGr** [comment]
Superseded by #3150. Thanks!

**Pull request closed without merging**
