### PR TITLE
2.0: Changes required to build on the 2.0 branch with gcc10

### PR DESCRIPTION
**Pull request by avsm**
These are the minimal changes the CI container images are using to continue building opam with Fedora 32 and other gcc10 arches.

- Change bootstrap compiler to 4.09.1
- Change distfile of extlib to a site that isnt down

### CODE REVIEW

**Comment by dra27** [comment]
I'm afraid it's more complex than this - I have a branch in progress!

**Comment by avsm** [comment]
This is what I'm using on the live container images -- so just Linux containers. It does work with the spectrum of images there, which is encouraging.

**Comment by dra27** [comment]
Indeed, but you're missing the fun of the Windows builds there - the build instructions changed at 4.08.0

**Comment by avsm** [comment]
Indeed - I just wanted this open to keep track of what's on live. Not necessary to merge it.

**Comment by dra27** [comment]
This is now subsumed by #4257

**Comment by dra27** [comment]
Sorry - this is the 2.0 version which is _not_ subsumed by #4257. Once CI finishes, I'll port the changes in `src_ext/Makefile` over to 2.0 (this will help the extlib problem by allowing fallback to the cache). The 4.09.1 advancing stuff in #4257 also needs merging.

**Comment by rjbou** [comment]
What is the status regarding 2.0.8 ? do we need to port #4257? @dra27

**Comment by dra27** [comment]
This is dealt with in 2.0 branch

**Pull request closed without merging**
