### PR TITLE
init: change shell setup defaut to true

### PR DESCRIPTION
**Pull request by rjbou**
It's less confusing for newcomers.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Should we also do the suggestions from https://github.com/ocaml/opam/issues/5401#issuecomment-1373892152 at the same time or leave it for later?

**Comment by rjbou** [comment]
let's add them here, to have a complete PR

**Comment by rjbou** [comment]
I can't approve as i opened the PR :) lgtm! thanks

**Review by kit-ty-kate — APPROVED** [review]

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
