### PR TITLE
Remove unnecessary copies/move when fetching archives

### LINKED ISSUE #5939: pin-depends system tries to remove part of the content
Issue encounted by @leostera during the mirageOS retreat

Reproducible minimal test case:
```
cd /tmp
mkdir srv
mkdir blah
mkdir blah/blah
echo 'opam-version: "2.0"' > blah/blah.opam
tar cvzf srv/blah blah/
cd srv
python3 -m http.server
```
```
$ cat test.opam
opam-version: "2.0"
pin-depends: [
  ["blah.dev" "http://localhost:8000/blah"]
]
```
```
$ opam pin .
Package test does not exist, create as a NEW package? [y/n] y
The following additional pinnings are required by test.dev:
  - blah.dev at http://localhost:8000/blah
Pin and install them? [y/n] y
Package blah does not exist, create as a NEW package? [y/n] y
[blah.dev] fetching sources failed: Download failed
[ERROR] Error getting source from http://localhost:8000/blah:
          - http://localhost:8000/blah (download failed)
```
using debug-level=3 you can see what actually fail:
```
error: Cannot remove ~/.opam/trunk/.opam-switch/sources/blah/blah (opam: "unlink" failed on ~/.opam/trunk/.opam-switch/sources/blah/blah: Is a directory).
```
It turns-out the pin-depends system seems to be downloading and extracting the pin-depends twice or something and failing because it's trying to remove a file that is currently a directory

Tested with both opam 2.1.5 and 2.2.0~beta2

### PR DESCRIPTION
**Pull request by kit-ty-kate**
In https://github.com/ocaml/opam/issues/4586#issuecomment-1018774363 we can see that to download an archive, opam currently does basically:
```
+ curl -L -o "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz.part" -- "${ARCHIVE}"
+ mv "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz.part" "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz"
+ mv "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz" "/tmp/opam-14-82d098/dune-2.9.1.tbz"
+ tar xfj /tmp/opam-14-82d098/dune-2.9.1.tbz -C /tmp/opam-14-1e6357
+ cp -PRp /tmp/opam-14-1e6357/dune-2.9.1/* /home/opam/.opam/4.13/.opam-switch/sources/dune.2.9.1
+ cp -PRp "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1" "${OPAM_SWITCH_PREFIX}/.opam-switch/build/dune.2.9.1"
```
The three first commands can be combined into one very easily, giving us:
```
+ curl -L -o /tmp/opam-14-82d098/dune-2.9.1.tbz.part -- "${ARCHIVE}"
+ mv /tmp/opam-14-82d098/dune-2.9.1.tbz.part /tmp/opam-14-82d098/dune-2.9.1.tbz
+ tar xfj /tmp/opam-14-82d098/dune-2.9.1.tbz -C /tmp/opam-14-1e6357
+ cp -PRp /tmp/opam-14-1e6357/dune-2.9.1/* /home/opam/.opam/4.13/.opam-switch/sources/dune.2.9.1
+ cp -PRp "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1" "${OPAM_SWITCH_PREFIX}/.opam-switch/build/dune.2.9.1"
```
Fixes #5939

### CODE REVIEW

**Comment by rjbou** [comment]
Reworked it, it was more tedious than at first sight

**Comment by rjbou** [comment]
thought: It complicates the code while it removes a unneeded `mv`.

**Review by rjbou — APPROVED** [review]
I've added a test to highlight the updates.
On my side, the code seems good. But from previous comments it seems that I wrote a part of it, so another air of eyes to look at, to the test too.

**Comment by kit-ty-kate** [comment]
lgtm now

**Pull request merged**
