### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by amirmc**
The current wording is confusing and
I think this is the intended meaning.

### CODE REVIEW

**Comment by amirmc** [comment]
Some more info. I just tried to do an opam upgrade and got a slightly confusing error message that says `The following dependencies are in cause:` (the full output is below for context) -- I'm guessing that's supposed to read "The following dependencies are the cause"?

```
[WARNING] A conflict was detected in your installation. This can be caused by updated constraints or conflicts in your installed packages:
            - Conflicting version constraints for mirage-types

The following dependencies are in cause:
  - mirage-types-lwt -> mirage-types < 2.4.0

You should run "opam upgrade" to resolve the situation.
```

**Comment by amirmc** [comment]
From Travis
```
+echo === OCaml version 4.02.3 ===
=== OCaml version 4.02.3 ===
+'[' 4.02.3 '!=' 4.02.1 ']'
+echo 'OCaml version doesn'\''t match: travis script needs fixing'
OCaml version doesn't match: travis script needs fixing
+exit 12
```

**Comment by amirmc** [comment]
see #2287

**Comment by amirmc** [comment]
And I've only just realised that this PR was made from a branch on *this* repo (not from my fork, as I expected). Sorry about that. Should be able to delete it after merge.

**Comment by AltGr** [comment]
> ```
> [WARNING] A conflict was detected in your installation. This can be caused by updated constraints > or conflicts in your installed packages:
>             - Conflicting version constraints for mirage-types
> 
> The following dependencies are in cause:
>   - mirage-types-lwt -> mirage-types < 2.4.0
> ```

Hm, this is a bit weird: normally you need at least two version constraints for them to be in conflict...
Can you give some more details on your request ? Is your `mirage-types` pinned ?

(just out of curiosity, I agree with the proposed change of wording)

**Comment by amirmc** [comment]
Just had this issue again with different packages, is this error message still odd to you?
`opam upgrade --fixup` resolved it by downgrading `dose` from `3.3` to `3.2.2+opam`.
```
[WARNING] A conflict was detected in your installation. This can be caused by updated constraints or conflicts in your installed packages:
            - Conflicting version constraints for ocamlgraph

The following dependencies are in cause:
  - dose -> ocamlgraph = 1.8.5

You should run "opam upgrade --fixup" to resolve the situation.
```

If you're happy with the proposed wording in the PR, then please merge and I can open another issue about the version constraints.

**Comment by amirmc** [comment]
I *think* the builds are breaking because the changes to the travis file need to be pulled into the relevant branch first (amirmc-patch-1).  I'll let someone else do this as I shouldn't be pushing to this repo.

**Pull request merged**
