### PR TITLE
lint W59/E60: don't check vcs upstream

### PR DESCRIPTION
**Pull request by rjbou**
Highlighted in https://github.com/ocurrent/opam-repo-ci/issues/93

### CODE REVIEW

**Comment by dra27** [comment]
What's actually checked with an rsync URL?

**Comment by dra27** [comment]
From dev meeting: the test needs to be http or rsync pointing to a file (rather than a directory)

**Comment by dra27** [comment]
This could potentially have a test for whether a checksum has been added when there _shouldn't_ be one

**Review by kit-ty-kate — APPROVED** [review]
Tested successfully and looks good to me overall. I think the details about rsync can be figured out later, it's less critical.

**Comment by dra27** [comment]
> I think the details about rsync can be figured out later, it's less critical.

The rsync file/directory part should be figured out now (we shouldn’t close one bug by creating another), but I agree the extra checksum check can wait. Regardless, please can issues be opened to track anything which isn’t fixed now 🙂

**Comment by rjbou** [comment]
Just finished both, no need of new issue :)
In fact the good check is too look is it is an archive url, regardless of the backend

**Comment by rjbou** [comment]
reviewed mechanism and add E67 for url present and no archive url

**Comment by kit-ty-kate** [comment]
I've tested a number of cases with it and it seems good to go for me.

**Pull request merged**
