### PR TITLE
Add ? operator to filter syntax

### PR DESCRIPTION
**Pull request by dra27**
See also https://github.com/ocaml/opam-file-format/pull/4 - this PR should have a commit updating `src_ext` before it is merged.

The `?` operator evaluates to false if the expression is undefined (i.e. contains undefined variables) and true in all other instances.

This operator removes the need for evil uses of `"%{variable}%"` (which expands to an empty string if variable is undefined). In particular, for the `ocaml-system` package, it allows a slightly less unclear `available` field:

```
available:
  sys-ocaml-version = "4.02.2" &
  !(?switch-arch & switch-arch != sys-ocaml-arch) &
  !(?switch-cc & switch-cc != sys-ocaml-cc) &
  !(?switch-libc & switch-libc != sys-ocaml-libc)
```

### CODE REVIEW

**Comment by dra27** [comment]
The two temporary commits are obviously just that, but note that https://github.com/ocaml/opam/pull/2921/commits/6b2a19fdf808fbf3d10cfbe9e6f4f8a15940a8dc includes changes which should be made, since lib-ext is presently using an older release of opam-file-format

**Comment by AltGr** [comment]
Thanks! We'll also need to update the doc (https://github.com/ocaml/opam/blob/master/doc/pages/Manual.md#filters and general syntax above)

**Comment by dra27** [comment]
Docs updated, and also the temporary lib-ext pointer changed.

Is there anything else I need to do to this one?

**Comment by AltGr** [comment]
Nope, seems all OK to me. The temporary commits actually don't need to be temporary anymore (it's fine to require the master version of opam-file-format for CI !)
Just waiting for Travis to complete

**Comment by AltGr** [comment]
Thanks!

**Pull request merged**
