### PR TITLE
Add base package new dependencies as base

### LINKED ISSUE #3662: Opam remove -a tries to remove ocaml-config and fails
It seems the `--auto-remove` option of `opam remove` does not cope very well with the new `ocaml-config` package.

This is triggered by the ocaml-ci `.travis-docker.sh` script and was first reported here: https://github.com/ocaml/ocaml-ci-scripts/issues/265
The issue contains all the details as to how to reproduce the bug.

It also looks similar to this issue: https://github.com/ocaml/opam/issues/3461

I may not understand the `--auto-remove` option very well but it seems to me that if a package can't be removed because other packages depend on it, the command shouldn't fail and simply leave the package alone since it's then not meant to be auto-removed isn't it?

### PR DESCRIPTION
**Pull request by rjbou**
When a base package is updated and have a new dependency, the latter is not added in the switch state compiler packages (base packages).  The fix checks and adds it/them, in the file `switch-state` too.
Fixes #3662 and related to #3666.

### CODE REVIEW

**Comment by dra27** [comment]
Huzzah!

<pre><font color="#8AE234"><b>dra@bionic</b></font>:<font color="#729FCF"><b>~/opam</b></font>$ ./opam upgrade -y
The following actions will be performed:
  <font color="#4E9A06">∗</font> install   <b>ocaml-config</b> 1
  <font color="#C4A000">↻</font> recompile <b>ocaml</b>        4.06.1
===== <font color="#4E9A06">∗</font> 1   <font color="#C4A000">↻</font> 1 =====

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Gathering sources</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Processing actions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">⊘</font> removed   <b>ocaml</b>.4.06.1
<font color="#4E9A06">∗</font> installed <b>ocaml-config</b>.1
<font color="#4E9A06">∗</font> installed <b>ocaml</b>.4.06.1
Done.
<font color="#8AE234"><b>dra@bionic</b></font>:<font color="#729FCF"><b>~/opam</b></font>$ ./opam list --base
# Packages matching: <font color="#06989A">base</font>
# Name        # Installed # Synopsis
<b>base-bigarray</b> <font color="#75507B">base</font>
<b>base-threads</b>  <font color="#75507B">base</font>
<b>base-unix</b>     <font color="#75507B">base</font>
<b>ocaml</b>         <font color="#75507B">4.06.1</font>      The OCaml compiler (virtual package)
<b>ocaml-config</b>  <font color="#75507B">1</font>           OCaml Switch Configuration
<u style="text-decoration-style:single"><b>ocaml-system</b></u>  <font color="#75507B">4.06.1</font>      The OCaml compiler (system version, from outside of opam)
</pre>

**Comment by dra27** [comment]
I think the two PRs together should sort this out! Given the effect on CI (and the nasty workaround editing the switch state), perhaps it would be worth shipping 2.0.2 soon with both of these?

**Comment by rjbou** [comment]
Yup, 2.0.2 on track!

**Comment by AltGr** [comment]
Closed as no longer necessary (underlying issue solved by #3670)

**Pull request closed without merging**
